%https://libgit2.github.com/libgit2/#HEAD/group/remote
%
%git_remote_add_fetch
%git_remote_add_push
%git_remote_autotag
%git_remote_connect - Open a connection to a remote
%git_remote_connected
%git_remote_create
%git_remote_create_anonymous
%git_remote_create_with_fetchspec
%git_remote_default_branch
%git_remote_delete
%git_remote_disconnect
%git_remote_download
%git_remote_dup
%git_remote_fetch
%git_remote_free
%git_remote_get_fetch_refspecs
%git_remote_get_push_refspecs
%git_remote_get_refspec
%git_remote_init_callbacks
%git_remote_is_valid_name
%git_remote_list
%git_remote_lookup
%git_remote_ls
%git_remote_name
%git_remote_owner
%git_remote_prune
%git_remote_prune_refs
%git_remote_push
%git_remote_refspec_count
%git_remote_rename
%git_remote_set_autotag
%git_remote_set_pushurl
%git_remote_set_url
%git_remote_stats - Get the statistics structure that is filled in by the fetch operation.
%git_remote_stop
%git_remote_update_tips - update the tips to the new state
%git_remote_upload
%git_remote_url
